# Site settings
title: Sea/Salt
email: hello@seasalt.io
description:  the technology team that can do anything. we help strong operators get new companies off the ground.
# baseurl: "http://seasalt.io"
url: "http://seasalt.io"

ga_id: "UA-59424309-1"

# Build settings
markdown: redcarpet
highlighter: pygments

sass:
  sass_dir: assets/_sass

exclude:
  - '*.haml'
  - '*.rb'
  - '*.coffee'
  - '*.yml'
  - '.fontcustom-manifest.json'
  - 'Guardfile'
  - 'Procfile'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Readme.md'
  - 'bower_components'
  - 'node_modules'
  - 'gulpfile.js'
  - 'package.json'
