# Site settings
title: Sea/Salt
email: hello@seasalt.io
description: It all starts with a product.
baseurl: "http://seasalt.io"
url: "http://seasalt.io"
twitter_username: seasalt_io

ga_id: "UA-59424309-1"
typekit_id: "ygs4xuv"

# Build settings
markdown: redcarpet
highlighter: pygments

exclude:
  - '*.haml'
  - '*.rb'
  - '*.coffee'
  - '*.yml'
  - '.fontcustom-manifest.json'
  - 'Guardfile'
  - 'Procfile'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Readme.md'
  - 'bower_components'
  - 'node_modules'
  - 'gulpfile.js'
  - 'package.json'
