# Site settings

url: "http://seasalt.io"

# Build settings
markdown: redcarpet
permalink: pretty

exclude:
  - '.DS_Store'
  - '*.haml'
  - 'bower_components'
  - 'node_modules'
  - '*.rb'
  - '*.coffee'
  - 'Guardfile'
  - 'Procfile'
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.yml'
  - 'app'
  - 'bower.json'
  - 'package.json'
  - 'Gruntfile.coffee'
  - '.fontcustom-manifest.json'


defaults:
  values:
    layout: "default"